### ISSUE TITLE
I get a porblem when I run, so I print (l1_loss.get_shape()) is  (?,).

### ISSUE THREAD

**Issue by heyang1021** [vicwer/C3AE_Age_Estimation#16]
@vicwer 
(3, 64, 64, 3)
conv_1 (?, 62, 62, 32)
avg_1 (?, 31, 31, 32)
conv_2 (?, 29, 29, 32)
avg_2 (?, 14, 14, 32)
conv_3 (?, 12, 12, 32)
avg_3 (?, 6, 6, 32)
conv_4 (?, 4, 4, 32)
reshape (?, 96)
fc_1 (?, 12)
fc_2 (?, 1)
Tensor("tower_0/C3AE/fc_1/kernel/Regularizer/l1_regularizer:0", shape=(), dtype=float32, device=/device:GPU:0)
l1_loss.get_shape():  (?,)
Traceback (most recent call last):
  File "multi_gpus_train.py", line 145, in <module>
    train(finetune=False)
  File "multi_gpus_train.py", line 97, in train
    loss = model.compute_loss()
  File "/home/zzjh08/C3AE/models/run_net.py", line 27, in compute_loss
    loss_l1 = l1_loss(self.pred, self.age_labels)
  File "/home/zzjh08/C3AE/models/losses.py", line 14, in l1_loss
    _, k_idx = tf.nn.top_k(l1_loss, tf.cast(tf.reduce_prod(l1_loss.get_shape()) * cfg.ohem_ratio, tf.int32))
  File "/home/zzjh08/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/zzjh08/.local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1543, in reduce_prod
    reduction_indices),
  File "/home/zzjh08/.local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1275, in _ReductionDims
    return range(0, array_ops.rank(x))
  File "/home/zzjh08/.local/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 368, in rank
    return rank_internal(input, name, optimize=True)
  File "/home/zzjh08/.local/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 388, in rank_internal
    input_tensor = ops.convert_to_tensor(input)
  File "/home/zzjh08/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1050, in convert_to_tensor
    as_ref=False)
  File "/home/zzjh08/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/zzjh08/.local/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 250, in _tensor_shape_tensor_conversion_function
    "Cannot convert a partially known TensorShape to a Tensor: %s" % s)
ValueError: Cannot convert a partially known TensorShape to a Tensor: (?,)

**Comment by vicwer** [comment]
@heyang1021 I have no machine, no dataset, so, u need fix it by yourself, sorry, and, good luck
